version: "3.8"

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: brevly-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - brevly

  server:
    build: .
    container_name: brevly-server
    depends_on:
      - pg
    restart: unless-stopped
    ports:
      - "3333:3333"
    env_file:
      - .env
    networks:
      - brevly

networks:
  brevly:
    driver: bridge
